// Generated by CoffeeScript 1.10.0
(function() {
  var Promise, _, fs, glob, less, log, moment;

  moment = require('moment');

  fs = require('fs');

  less = require('less');

  Promise = require('rsvp').Promise;

  glob = require('glob');

  _ = require('lodash');

  log = require('../log');

  module.exports = function(ctx) {
    var startedAt;
    startedAt = moment();
    return new Promise(function(resolve, reject) {
      var files, paths, rootFileInfo, src;
      files = glob.sync(ctx.args.srcDir + "/**/*.+(less|css)");
      src = _.reduce(files, function(src, path) {
        return src + fs.readFileSync(path);
      }, '');
      rootFileInfo = {
        currentDirectory: ctx.args.srcDir,
        rootPath: ctx.args.srcDir,
        relativeUrls: true
      };
      paths = [ctx.args.bowerDir];
      return less.render(src, {
        rootFileInfo: rootFileInfo,
        paths: paths
      }).then(function(arg) {
        var css, map;
        css = arg.css, map = arg.map;
        fs.writeFileSync(ctx.args.buildDir + "/css/all.css", css);
        log.debug("Finished compiling styles in " + (moment().diff(startedAt)) + "ms");
        return resolve(ctx);
      }).then(null, function(err) {
        return log.debug("Error compiling styles: " + err);
      });
    });
  };

}).call(this);
