// Generated by CoffeeScript 1.7.1
(function() {
  var Promise, fs, glob, less, log, moment, _;

  moment = require('moment');

  fs = require('fs');

  less = require('less');

  Promise = require('rsvp').Promise;

  glob = require('glob');

  _ = require('lodash');

  log = require('../log');

  module.exports = function(ctx) {
    var startedAt;
    startedAt = moment();
    return new Promise(function(resolve, reject) {
      var files, parser, src;
      files = glob.sync("" + ctx.args.srcDir + "/**/*.+(less|css)");
      src = _.reduce(files, function(src, path) {
        return src + fs.readFileSync(path);
      }, '');
      parser = new less.Parser({
        paths: [ctx.args.srcDir, ctx.args.bowerDir],
        filename: 'bundle.less'
      });
      return parser.parse(src, function(err, tree) {
        var css;
        if (err) {
          return reject(err);
        } else {
          css = tree.toCSS({
            compress: ctx.args.compress
          });
          fs.writeFileSync("" + ctx.args.buildDir + "/css/all.css", css);
          log.debug("Finished compiling styles in " + (moment().diff(startedAt)) + "ms");
          return resolve(ctx);
        }
      });
    });
  };

}).call(this);
