// Generated by CoffeeScript 1.7.0
(function() {
  var util, yargs, _;

  util = require('util');

  _ = require('lodash');

  yargs = require('yargs');

  module.exports = {
    run: function() {
      var args, cwd;
      cwd = process.cwd();
      args = yargs["default"]('bowerDir', "" + cwd + "/bower_components")["default"]('srcDir', "" + cwd + "/fe")["default"]('buildDir', "" + cwd + "/public")["default"]('mainScript', "fe.coffee").alias({
        srcDir: 's',
        buildDir: 'b',
        mainScript: 'm'
      }).argv;
      return _.each(args._, function(command) {
        return require("./" + command).run(args);
      });
    }
  };

}).call(this);
