// Generated by CoffeeScript 1.7.1
(function() {
  var build, devArgs, log, path, yargs, _;

  path = require('path');

  _ = require('lodash');

  yargs = require('yargs');

  log = require('./log');

  build = require('./build');

  devArgs = yargs["default"]('port', process.env.PORT || 8000)["default"]('serve', true).argv;

  module.exports = {
    run: function(args) {
      var building, rebuild;
      _.defaults(args, devArgs);
      args.renderDrafts = true;
      building = false;
      rebuild = function(cb) {
        if (!building) {
          building = true;
          return build.run(args).then(function() {
            building = false;
            return typeof cb === "function" ? cb() : void 0;
          }).then(null, function(err) {
            log("Error during build: " + err);
            return process.exit(1);
          });
        }
      };
      process.stdin.resume();
      process.stdin.on('data', function() {
        return rebuild();
      });
      return rebuild(function() {
        var connect;
        if (args.serve) {
          connect = require('connect');
          connect().use(connect["static"]('./public')).listen(args.port);
          log("Dev server listening on port " + args.port);
        }
        log("Press return to rebuild");
        return (require('gaze'))("" + args.srcDir + "/**", function(err, watcher) {
          return this.on('all', function() {
            return rebuild();
          });
        });
      });
    }
  };

}).call(this);
