// Generated by CoffeeScript 1.7.0
(function() {
  var createLogFns, inspect, log, n, opts, timestamp, _,
    __slice = [].slice;

  _ = require('lodash');

  inspect = require('util').inspect;

  opts = {
    timeFormat: "HH:mm:ss",
    defaultLevel: 'info',
    threshold: 'debug',
    levels: ['trace', 'debug', 'info', 'warn', 'error']
  };

  n = function(level) {
    return opts.levels.indexOf(level);
  };

  timestamp = function() {
    return require('moment')().format(opts.timeFormat);
  };

  createLogFns = function() {
    return _.reduce(opts.levels, function(fns, level) {
      fns[level] = function() {
        var msg;
        msg = 1 <= arguments.length ? __slice.call(arguments, 0) : [];
        msg = _.map(msg, function(item) {
          if (typeof item === 'string') {
            return item;
          } else {
            return inspect(item);
          }
        });
        if (n(level) >= n(opts.threshold)) {
          return console.log("" + (timestamp()) + " " + (msg.join()));
        }
      };
      return fns;
    }, {});
  };

  log = function() {
    var msg;
    msg = 1 <= arguments.length ? __slice.call(arguments, 0) : [];
    return log[opts.defaultLevel].apply(log, msg);
  };

  _.extend(log, createLogFns(), {
    setThreshold: function(threshold) {
      return opts.threshold = threshold;
    },
    setLevels: function() {
      var levels;
      levels = 1 <= arguments.length ? __slice.call(arguments, 0) : [];
      _.each(opts.levels, function(level) {
        return delete log[level];
      });
      opts.levels = levels;
      return _.extend(log, createLogFns());
    }
  });

  module.exports = log;

}).call(this);
